export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL'

export const PRODUCT_BY_ID_REQUEST = 'PRODUCT_BY_ID_REQUEST'
export const PRODUCT_BY_ID_SUCCESS = 'PRODUCT_BY_ID_SUCCESS'
export const PRODUCT_BY_ID_FAIL = 'PRODUCT_BY_ID_FAIL'

export const PRODUCT_ADD_ITEM = 'PRODUCT_ADD_ITEM'
export const PRODUCT_SHOW = 'PRODUCT_SHOW'